import type { Config } from 'payload'

type AdminComponentOverrides = {
  beforeNavLinks?: string[]
  dashboard?: string
  icon?: string
  logo?: string
}

/**
 * Returns admin component path configuration for Payload's custom components system.
 *
 * Exports component paths following Payload's component path syntax.
 * These are resolved via the importMap.js file generated by Payload.
 *
 * Components:
 * - beforeNavLinks: Custom navigation panel before the built-in nav links (AdminNavPanel)
 * - dashboard: Custom dashboard view - replaces the default dashboard (AdminDashboardView)
 * - icon: Icon used in the navigation sidebar (ProjectsIcon)
 * - logo: Logo displayed on the login page (AdminLogo)
 *
 * Pass overrides to replace individual components:
 *   getAdminComponents({ logo: './src/components/MyLogo#MyLogo' })
 */
export function getAdminComponents(overrides: AdminComponentOverrides = {}): Config['admin']['components'] {
  return {
    // Custom navigation panel before the built-in nav links
    beforeNavLinks: overrides.beforeNavLinks ?? ['@loom/payload-admin#AdminNavPanel'],
    // Custom dashboard view - replaces the default dashboard
    views: {
      dashboard: {
        Component: overrides.dashboard ?? '@loom/payload-admin#AdminDashboardView',
      },
    },
    // Custom graphics for logo and icon
    graphics: {
      // Icon used in the navigation sidebar
      Icon: overrides.icon ?? '@loom/payload-admin#ProjectsIcon',
      // Logo displayed on the login page
      Logo: overrides.logo ?? '@loom/payload-admin#AdminLogo',
    },
  }
}
