/**
 * @loom/payload-admin - LOOM Studios custom Payload CMS admin panel
 * 
 * This package exports custom admin components for Payload CMS using Payload's
 * custom components system. Components are loaded via component paths and resolved
 * through the importMap.js file generated by Payload at build time.
 * 
 * Usage:
 *   import { getAdminComponents } from '@loom/payload-admin/config'
 *   
 *   export default buildConfig({
 *     admin: {
 *       components: getAdminComponents()
 *     }
 *   })
 */

// Export component configuration function for use in payload.config.ts
export { getAdminComponents } from './config'

// Export all admin UI components as named exports
// These are resolved by Payload's importMap.js system using the # syntax
// e.g., '@loom/payload-admin#AdminNavPanel'
export { AdminNavPanel } from './AdminNavPanel'
export { AdminDashboardView } from './AdminDashboardView'
export { AdminLogo } from './AdminLogo'
export { ProjectsIcon } from './ProjectsIcon'
export { AdminLayout } from './AdminLayout'
export { AdminSidebar } from './AdminSidebar'
